2022-09-08 10:54:38,299 - [test_login.py-->line:37] - INFO: 用例--【登录成功】---执行通过
2022-09-08 10:54:38,365 - [test_login.py-->line:37] - INFO: 用例--【账号为空】---执行通过
2022-09-08 10:54:38,437 - [test_login.py-->line:37] - INFO: 用例--【密码为空 】---执行通过
2022-09-08 10:54:38,522 - [test_login.py-->line:37] - INFO: 用例--【密码错误】---执行通过
2022-09-08 10:54:38,612 - [test_login.py-->line:37] - INFO: 用例--【密码错误2】---执行通过
2022-09-08 10:54:38,700 - [test_login.py-->line:37] - INFO: 用例--【密码错误3】---执行通过
2022-09-08 10:54:39,059 - [test_recharge.py-->line:75] - INFO: 用例--【充值成功】---执行通过
2022-09-08 10:54:39,379 - [test_recharge.py-->line:75] - INFO: 用例--【 id错误】---执行通过
2022-09-08 10:54:39,606 - [test_recharge.py-->line:75] - INFO: 用例--【不输入id】---执行通过
2022-09-08 10:54:39,860 - [test_recharge.py-->line:71] - ERROR: 用例--【不输入金额】---执行失败
2022-09-08 10:54:39,860 - [test_recharge.py-->line:72] - ERROR: 1 != 0
Traceback (most recent call last):
  File "C:\Users\ZLD\PycharmProjects\Learn\Testcases\test_recharge.py", line 64, in test_recharge
    self.assertEqual(expected["code"], res["code"])
  File "C:\Python310\lib\unittest\case.py", line 845, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\Python310\lib\unittest\case.py", line 838, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 0
2022-09-08 10:54:40,143 - [test_recharge.py-->line:75] - INFO: 用例--【充值金额为负数】---执行通过
2022-09-08 10:54:40,433 - [test_recharge.py-->line:75] - INFO: 用例--【充值金额为9000000】---执行通过
2022-09-08 10:54:40,707 - [test_recharge.py-->line:75] - INFO: 用例--【充值金额非数字】---执行通过
2022-09-08 10:54:40,833 - [test_reqister.py-->line:43] - INFO: 用例--【注册成功-带用户名】---执行通过
2022-09-08 10:54:40,940 - [test_reqister.py-->line:43] - INFO: 用例--【注册成功-带不用户名】---执行通过
2022-09-08 10:54:41,021 - [test_reqister.py-->line:43] - INFO: 用例--【不输入手机号】---执行通过
2022-09-08 10:54:41,104 - [test_reqister.py-->line:43] - INFO: 用例--【 手机号长度10位】---执行通过
2022-09-08 10:54:41,190 - [test_reqister.py-->line:43] - INFO: 用例--【 手机号长度12位】---执行通过
2022-09-08 10:54:41,271 - [test_reqister.py-->line:43] - INFO: 用例--【手机号含非法字符】---执行通过
2022-09-08 10:54:41,372 - [test_reqister.py-->line:43] - INFO: 用例--【 已经注册的手机号】---执行通过
2022-09-08 10:54:41,599 - [test_withraw.py-->line:62] - INFO: 用例--【提现成功】---执行通过
2022-09-08 10:54:41,695 - [test_withraw.py-->line:62] - INFO: 用例--【提现成功-1位小数】---执行通过
2022-09-08 10:54:41,791 - [test_withraw.py-->line:62] - INFO: 用例--【提现成功-2位小数】---执行通过
2022-09-08 10:54:41,889 - [test_withraw.py-->line:62] - INFO: 用例--【提现成功-50万】---执行通过
2022-09-08 10:54:41,957 - [test_withraw.py-->line:62] - INFO: 用例--【会员id为空】---执行通过
2022-09-08 10:54:42,030 - [test_withraw.py-->line:62] - INFO: 用例--【提现金额为空】---执行通过
2022-09-08 10:54:42,096 - [test_withraw.py-->line:62] - INFO: 用例--【提现金额为-6位小数】---执行通过
2022-09-08 10:54:42,165 - [test_withraw.py-->line:62] - INFO: 用例--【提现金额为大于50万】---执行通过
2022-09-08 10:54:42,226 - [test_withraw.py-->line:62] - INFO: 用例--【 提现金额非数字】---执行通过
2022-09-08 16:11:08,835 - [test_recharge.py-->line:78] - INFO: 用例--【充值成功】---执行通过
2022-09-08 16:11:09,054 - [test_recharge.py-->line:78] - INFO: 用例--【 id错误】---执行通过
2022-09-08 16:11:09,273 - [test_recharge.py-->line:78] - INFO: 用例--【不输入id】---执行通过
2022-09-08 16:11:09,503 - [test_recharge.py-->line:74] - ERROR: 用例--【不输入金额】---执行失败
2022-09-08 16:11:09,503 - [test_recharge.py-->line:75] - ERROR: 1 != 0
Traceback (most recent call last):
  File "C:\Users\ZLD\PycharmProjects\Learn\Testcases\test_recharge.py", line 67, in test_recharge
    self.assertEqual(expected["code"], res["code"])
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2022.1.3\plugins\python-ce\helpers\pycharm\teamcity\diff_tools.py", line 33, in _patched_equals
    old(self, first, second, msg)
  File "C:\Python310\lib\unittest\case.py", line 845, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\Python310\lib\unittest\case.py", line 838, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 0
2022-09-08 16:11:09,723 - [test_recharge.py-->line:78] - INFO: 用例--【充值金额为负数】---执行通过
2022-09-08 16:11:09,957 - [test_recharge.py-->line:78] - INFO: 用例--【充值金额为9000000】---执行通过
2022-09-08 16:11:10,178 - [test_recharge.py-->line:78] - INFO: 用例--【充值金额非数字】---执行通过
2022-09-08 16:11:16,628 - [test_recharge.py-->line:78] - INFO: 用例--【充值成功】---执行通过
2022-09-08 16:11:16,842 - [test_recharge.py-->line:78] - INFO: 用例--【 id错误】---执行通过
2022-09-08 16:11:17,066 - [test_recharge.py-->line:78] - INFO: 用例--【不输入id】---执行通过
2022-09-08 16:11:17,296 - [test_recharge.py-->line:74] - ERROR: 用例--【不输入金额】---执行失败
2022-09-08 16:11:17,296 - [test_recharge.py-->line:75] - ERROR: 1 != 0
Traceback (most recent call last):
  File "C:\Users\ZLD\PycharmProjects\Learn\Testcases\test_recharge.py", line 67, in test_recharge
    self.assertEqual(expected["code"], res["code"])
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2022.1.3\plugins\python-ce\helpers\pycharm\teamcity\diff_tools.py", line 33, in _patched_equals
    old(self, first, second, msg)
  File "C:\Python310\lib\unittest\case.py", line 845, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\Python310\lib\unittest\case.py", line 838, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 0
2022-09-08 16:11:17,515 - [test_recharge.py-->line:78] - INFO: 用例--【充值金额为负数】---执行通过
2022-09-08 16:11:17,731 - [test_recharge.py-->line:78] - INFO: 用例--【充值金额为9000000】---执行通过
2022-09-08 16:11:17,946 - [test_recharge.py-->line:78] - INFO: 用例--【充值金额非数字】---执行通过
2022-09-08 16:11:48,479 - [test_recharge.py-->line:78] - INFO: 用例--【充值成功】---执行通过
2022-09-08 16:11:48,691 - [test_recharge.py-->line:78] - INFO: 用例--【 id错误】---执行通过
2022-09-08 16:11:48,911 - [test_recharge.py-->line:78] - INFO: 用例--【不输入id】---执行通过
2022-09-08 16:11:49,135 - [test_recharge.py-->line:74] - ERROR: 用例--【不输入金额】---执行失败
2022-09-08 16:11:49,135 - [test_recharge.py-->line:75] - ERROR: 1 != 0
Traceback (most recent call last):
  File "C:\Users\ZLD\PycharmProjects\Learn\Testcases\test_recharge.py", line 67, in test_recharge
    self.assertEqual(expected["code"], res["code"])
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2022.1.3\plugins\python-ce\helpers\pycharm\teamcity\diff_tools.py", line 33, in _patched_equals
    old(self, first, second, msg)
  File "C:\Python310\lib\unittest\case.py", line 845, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\Python310\lib\unittest\case.py", line 838, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 0
2022-09-08 16:11:49,349 - [test_recharge.py-->line:78] - INFO: 用例--【充值金额为负数】---执行通过
2022-09-08 16:11:49,566 - [test_recharge.py-->line:78] - INFO: 用例--【充值金额为9000000】---执行通过
2022-09-08 16:11:49,784 - [test_recharge.py-->line:78] - INFO: 用例--【充值金额非数字】---执行通过
2022-09-08 16:12:10,786 - [test_recharge.py-->line:78] - INFO: 用例--【充值成功】---执行通过
2022-09-08 16:12:10,991 - [test_recharge.py-->line:78] - INFO: 用例--【 id错误】---执行通过
2022-09-08 16:12:11,197 - [test_recharge.py-->line:78] - INFO: 用例--【不输入id】---执行通过
2022-09-08 16:12:11,435 - [test_recharge.py-->line:74] - ERROR: 用例--【不输入金额】---执行失败
2022-09-08 16:12:11,435 - [test_recharge.py-->line:75] - ERROR: 1 != 0
Traceback (most recent call last):
  File "C:\Users\ZLD\PycharmProjects\Learn\Testcases\test_recharge.py", line 67, in test_recharge
    self.assertEqual(expected["code"], res["code"])
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2022.1.3\plugins\python-ce\helpers\pycharm\teamcity\diff_tools.py", line 33, in _patched_equals
    old(self, first, second, msg)
  File "C:\Python310\lib\unittest\case.py", line 845, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\Python310\lib\unittest\case.py", line 838, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 0
2022-09-08 16:12:11,632 - [test_recharge.py-->line:78] - INFO: 用例--【充值金额为负数】---执行通过
2022-09-08 16:12:11,835 - [test_recharge.py-->line:78] - INFO: 用例--【充值金额为9000000】---执行通过
2022-09-08 16:12:12,045 - [test_recharge.py-->line:78] - INFO: 用例--【充值金额非数字】---执行通过
2022-09-08 16:12:30,072 - [test_recharge.py-->line:78] - INFO: 用例--【充值成功】---执行通过
2022-09-08 16:12:30,285 - [test_recharge.py-->line:78] - INFO: 用例--【 id错误】---执行通过
2022-09-08 16:12:30,495 - [test_recharge.py-->line:78] - INFO: 用例--【不输入id】---执行通过
2022-09-08 16:12:30,712 - [test_recharge.py-->line:74] - ERROR: 用例--【不输入金额】---执行失败
2022-09-08 16:12:30,712 - [test_recharge.py-->line:75] - ERROR: 1 != 0
Traceback (most recent call last):
  File "C:\Users\ZLD\PycharmProjects\Learn\Testcases\test_recharge.py", line 67, in test_recharge
    self.assertEqual(expected["code"], res["code"])
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2022.1.3\plugins\python-ce\helpers\pycharm\teamcity\diff_tools.py", line 33, in _patched_equals
    old(self, first, second, msg)
  File "C:\Python310\lib\unittest\case.py", line 845, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\Python310\lib\unittest\case.py", line 838, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 0
2022-09-08 16:12:30,914 - [test_recharge.py-->line:78] - INFO: 用例--【充值金额为负数】---执行通过
2022-09-08 16:12:31,120 - [test_recharge.py-->line:78] - INFO: 用例--【充值金额为9000000】---执行通过
2022-09-08 16:12:31,318 - [test_recharge.py-->line:78] - INFO: 用例--【充值金额非数字】---执行通过
2022-09-08 16:28:29,138 - [test_withraw.py-->line:64] - INFO: 用例--【提现成功】---执行通过
2022-09-08 16:28:29,215 - [test_withraw.py-->line:64] - INFO: 用例--【提现成功-1位小数】---执行通过
2022-09-08 16:28:29,293 - [test_withraw.py-->line:64] - INFO: 用例--【提现成功-2位小数】---执行通过
2022-09-08 16:28:29,375 - [test_withraw.py-->line:64] - INFO: 用例--【提现成功-50万】---执行通过
2022-09-08 16:28:29,445 - [test_withraw.py-->line:64] - INFO: 用例--【会员id为空】---执行通过
2022-09-08 16:28:29,521 - [test_withraw.py-->line:64] - INFO: 用例--【提现金额为空】---执行通过
2022-09-08 16:28:29,588 - [test_withraw.py-->line:64] - INFO: 用例--【提现金额为-6位小数】---执行通过
2022-09-08 16:28:29,658 - [test_withraw.py-->line:64] - INFO: 用例--【提现金额为大于50万】---执行通过
2022-09-08 16:28:29,725 - [test_withraw.py-->line:64] - INFO: 用例--【 提现金额非数字】---执行通过
2022-09-08 16:29:03,249 - [test_reqister.py-->line:43] - INFO: 用例--【不输入手机号】---执行通过
2022-09-08 16:29:03,315 - [test_reqister.py-->line:43] - INFO: 用例--【 手机号长度10位】---执行通过
2022-09-08 16:29:03,388 - [test_reqister.py-->line:43] - INFO: 用例--【 手机号长度12位】---执行通过
2022-09-08 16:29:03,453 - [test_reqister.py-->line:43] - INFO: 用例--【手机号含非法字符】---执行通过
2022-09-08 16:29:03,541 - [test_reqister.py-->line:43] - INFO: 用例--【 已经注册的手机号】---执行通过
2022-09-08 16:29:38,103 - [test_reqister.py-->line:43] - INFO: 用例--【注册成功-带用户名】---执行通过
2022-09-08 16:29:38,202 - [test_reqister.py-->line:43] - INFO: 用例--【注册成功-带不用户名】---执行通过
2022-09-08 16:29:38,269 - [test_reqister.py-->line:43] - INFO: 用例--【不输入手机号】---执行通过
2022-09-08 16:29:38,336 - [test_reqister.py-->line:43] - INFO: 用例--【 手机号长度10位】---执行通过
2022-09-08 16:29:38,398 - [test_reqister.py-->line:43] - INFO: 用例--【 手机号长度12位】---执行通过
2022-09-08 16:29:38,459 - [test_reqister.py-->line:43] - INFO: 用例--【手机号含非法字符】---执行通过
2022-09-08 16:29:38,548 - [test_reqister.py-->line:43] - INFO: 用例--【 已经注册的手机号】---执行通过
2022-09-08 16:29:50,855 - [test_login.py-->line:37] - INFO: 用例--【登录成功】---执行通过
2022-09-08 16:29:50,927 - [test_login.py-->line:37] - INFO: 用例--【账号为空】---执行通过
2022-09-08 16:29:50,998 - [test_login.py-->line:37] - INFO: 用例--【密码为空 】---执行通过
2022-09-08 16:29:51,086 - [test_login.py-->line:37] - INFO: 用例--【密码错误】---执行通过
2022-09-08 16:29:51,168 - [test_login.py-->line:37] - INFO: 用例--【密码错误2】---执行通过
2022-09-08 16:29:51,251 - [test_login.py-->line:37] - INFO: 用例--【密码错误3】---执行通过
2022-09-08 16:29:51,557 - [test_recharge.py-->line:75] - INFO: 用例--【充值成功】---执行通过
2022-09-08 16:29:51,775 - [test_recharge.py-->line:75] - INFO: 用例--【 id错误】---执行通过
2022-09-08 16:29:52,373 - [test_recharge.py-->line:75] - INFO: 用例--【不输入id】---执行通过
2022-09-08 16:29:52,790 - [test_recharge.py-->line:71] - ERROR: 用例--【不输入金额】---执行失败
2022-09-08 16:29:52,790 - [test_recharge.py-->line:72] - ERROR: 1 != 0
Traceback (most recent call last):
  File "C:\Users\ZLD\PycharmProjects\Learn\Testcases\test_recharge.py", line 64, in test_recharge
    self.assertEqual(expected["code"], res["code"])
  File "C:\Python310\lib\unittest\case.py", line 845, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\Python310\lib\unittest\case.py", line 838, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 0
2022-09-08 16:29:53,203 - [test_recharge.py-->line:75] - INFO: 用例--【充值金额为负数】---执行通过
2022-09-08 16:29:53,607 - [test_recharge.py-->line:75] - INFO: 用例--【充值金额为9000000】---执行通过
2022-09-08 16:29:54,021 - [test_recharge.py-->line:75] - INFO: 用例--【充值金额非数字】---执行通过
2022-09-08 16:29:54,348 - [test_reqister.py-->line:43] - INFO: 用例--【注册成功-带用户名】---执行通过
2022-09-08 16:29:54,439 - [test_reqister.py-->line:43] - INFO: 用例--【注册成功-带不用户名】---执行通过
2022-09-08 16:29:54,616 - [test_reqister.py-->line:43] - INFO: 用例--【不输入手机号】---执行通过
2022-09-08 16:29:54,795 - [test_reqister.py-->line:43] - INFO: 用例--【 手机号长度10位】---执行通过
2022-09-08 16:29:54,963 - [test_reqister.py-->line:43] - INFO: 用例--【 手机号长度12位】---执行通过
2022-09-08 16:29:55,028 - [test_reqister.py-->line:43] - INFO: 用例--【手机号含非法字符】---执行通过
2022-09-08 16:29:55,221 - [test_reqister.py-->line:43] - INFO: 用例--【 已经注册的手机号】---执行通过
2022-09-08 16:29:55,621 - [test_withraw.py-->line:64] - INFO: 用例--【提现成功】---执行通过
2022-09-08 16:29:55,782 - [test_withraw.py-->line:64] - INFO: 用例--【提现成功-1位小数】---执行通过
2022-09-08 16:29:55,867 - [test_withraw.py-->line:64] - INFO: 用例--【提现成功-2位小数】---执行通过
2022-09-08 16:29:56,072 - [test_withraw.py-->line:64] - INFO: 用例--【提现成功-50万】---执行通过
2022-09-08 16:29:56,259 - [test_withraw.py-->line:64] - INFO: 用例--【会员id为空】---执行通过
2022-09-08 16:29:56,323 - [test_withraw.py-->line:64] - INFO: 用例--【提现金额为空】---执行通过
2022-09-08 16:29:56,397 - [test_withraw.py-->line:64] - INFO: 用例--【提现金额为-6位小数】---执行通过
2022-09-08 16:29:56,461 - [test_withraw.py-->line:64] - INFO: 用例--【提现金额为大于50万】---执行通过
2022-09-08 16:29:56,524 - [test_withraw.py-->line:64] - INFO: 用例--【 提现金额非数字】---执行通过
2022-09-08 16:40:20,018 - [test_reqister.py-->line:43] - INFO: 用例--【注册成功-带用户名】---执行通过
2022-09-08 16:40:20,121 - [test_reqister.py-->line:43] - INFO: 用例--【注册成功-带不用户名】---执行通过
2022-09-08 16:40:20,190 - [test_reqister.py-->line:43] - INFO: 用例--【不输入手机号】---执行通过
2022-09-08 16:40:20,260 - [test_reqister.py-->line:43] - INFO: 用例--【 手机号长度10位】---执行通过
2022-09-08 16:40:20,326 - [test_reqister.py-->line:43] - INFO: 用例--【 手机号长度12位】---执行通过
2022-09-08 16:40:20,395 - [test_reqister.py-->line:43] - INFO: 用例--【手机号含非法字符】---执行通过
2022-09-08 16:40:20,484 - [test_reqister.py-->line:43] - INFO: 用例--【 已经注册的手机号】---执行通过
2022-09-08 16:41:04,334 - [test_reqister.py-->line:43] - INFO: 用例--【注册成功-带用户名】---执行通过
2022-09-08 16:41:04,426 - [test_reqister.py-->line:43] - INFO: 用例--【注册成功-带不用户名】---执行通过
2022-09-08 16:41:04,490 - [test_reqister.py-->line:43] - INFO: 用例--【不输入手机号】---执行通过
2022-09-08 16:41:04,557 - [test_reqister.py-->line:43] - INFO: 用例--【 手机号长度10位】---执行通过
2022-09-08 16:41:04,626 - [test_reqister.py-->line:43] - INFO: 用例--【 手机号长度12位】---执行通过
2022-09-08 16:41:04,688 - [test_reqister.py-->line:43] - INFO: 用例--【手机号含非法字符】---执行通过
2022-09-08 16:41:04,788 - [test_reqister.py-->line:43] - INFO: 用例--【 已经注册的手机号】---执行通过
